<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 11 Jul 2016 19:19:18 +0000
 */

$conf['title'] = 'Supercomputacion';
$conf['lang'] = 'es';
$conf['template'] = 'arctic';
$conf['license'] = '0';
$conf['dmode'] = 0770;
$conf['fmode'] = 0660;
$conf['youarehere'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['fetchsize'] = 512000;
$conf['proxy']['host'] = 'proxy.aemet.es';
$conf['proxy']['port'] = 3128;
$conf['proxy']['user'] = 'tshpc1';
$conf['proxy']['pass'] = '<b>QnVsbDIwMTQ=';
$conf['plugin']['tools']['show_link'] = '2';
$conf['plugin']['legalnotice']['text'] = '{{:1417201828_1.png?direct |}}';
$conf['plugin']['wikicalendar']['timezone'] = 'Europe/Madrid';
$conf['tpl']['arctic']['sidebar'] = 'none';
$conf['tpl']['arctic']['main_sidebar_always'] = 0;
$conf['tpl']['arctic']['wiki_actionlinks'] = 'buttons';
$conf['tpl']['arctic']['search'] = 'right';
$conf['tpl']['arctic']['closedwiki'] = 1;
$conf['tpl']['arctic']['hideactions'] = 1;
$conf['plugin']['authmysql']['TablesToLock'] = '';
$conf['plugin']['snow']['enabled'] = '0';
$conf['tpl']['zenlike']['hideTools'] = '1';
$conf['tpl']['mnml-blog']['mnmlblog_sidebarnav'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_copyright'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_copyright_default'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_search'] = '0';
$conf['tpl']['mnml-blog']['mnmlblog_qrcodebox'] = '0';
$conf['tpl']['dokubootstrapsimplified']['bootswatch'] = 'united';
$conf['tpl']['dokubook']['sb_pagename'] = 'sidebar';
$conf['tpl']['dokubook']['closedwiki'] = '1';
$conf['tpl']['dokubook']['logo'] = './data/media/wiki/aemet4.png';
$conf['tpl']['dokuwikitemplatedokubrickmaster']['sidebar_content'] = 'toc,main,user,group,namespace,index';
$conf['tpl']['scanlines']['sidebar'] = 'none';
$conf['tpl']['scanlines']['main_sidebar_always'] = '0';
$conf['tpl']['scanlines']['left_sidebar_content'] = 'main,toc,index,extra';
$conf['tpl']['scanlines']['right_sidebar_content'] = 'main,toc,index,extra';
$conf['tpl']['scanlines']['sitemap'] = '0';
$conf['tpl']['scanlines']['top_link'] = '0';

// end auto-generated content
